# Generated by Django 6.0.7 on 2026-07-29 10:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, editable=False, help_text='Human-friendly code (e.g. MED-0001) — easy to search/reference at the pharmacy counter.', max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier', models.CharField(max_length=150)),
                ('expiry_date', models.DateField()),
                ('reorder_level', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
